version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/UTN-TPA/Pulumi
    steps:
      - setup_remote_docker
      - checkout:
          path: ~/UTN-TPA
      - run:
          name: "Install Pulumi SDK"
          command: |
              npm i @pulumi/pulumi
              npm i @pulumi/aws
      - run:
          name: "Install Pulumi CLI"
          command: |
              curl -L https://get.pulumi.com/ | bash -s
              # Add to PATH
              echo 'export PATH=${HOME}/.pulumi/bin:$PATH' >> $BASH_ENV
              source $BASH_ENV
      - run:
          name: "Log into Pulumi"
          command: |
            export PULUMI_ACCESS_TOKEN="${PULUMI_ACCESS_TOKEN}"
            pulumi login --cloud-url https://api.pulumi.com
      # - run:
      #     name: "Log into Docker"
      #     command: | 
      #       aws ecr get-login-password -region us-east-1 | docker login -username AWS -password-stdin "684774864993".dkr.ecr.us-east-1.amazonaws.com
      - run:
          name: "Run Pulumi"
          command: |
            pulumi up --yes --skip-preview --stack dev --cwd ~/UTN-TPA/Pulumi